#Build the docker 
name: Deploy Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.frontend
          build-args: 
            - DATABASE_URL=${{ secrets.DATABASE_URL }} 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{github.sha}}


